server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MarinaSpanenberg/microservices-java
          default-label: main
          search-paths:
            - 'configs/{application}'

